export enum TIME_RESOLUTION_ENUM {
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
  YEAR = 'YEAR',
}

export enum MAINTENANCE_TYPE_ENUM {
  PREVENTIVE = 'PREVENTIVE',
  CORRECTIVE = 'CORRECTIVE',
}

export enum WORK_ORDER_PRIORITY {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum WORK_ORDER_STATUS {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  INSPECTION = 'INSPECTION',
  COMPLETED = 'COMPLETED',
  VERIFIED = 'VERIFIED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum SCHEDULE_STATUS {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ANALYTICS_AUDIT_ACTION {
  ANALYTICS_REPORT_VIEWED = 'ANALYTICS_REPORT_VIEWED',
  ANALYTICS_REPORT_EXPORTED = 'ANALYTICS_REPORT_EXPORTED',
}

export enum WORK_ORDER_CLASSIFICATION {
  PREVENTIVE = 'PREVENTIVE',
  CORRECTIVE = 'CORRECTIVE',
  UNCLASSIFIED = 'UNCLASSIFIED',
  CONFLICTED = 'CONFLICTED',
}

/**
 * Shared uniform constant list of "Completed" Work Order statuses across all KPI calculations.
 */
export const COMPLETED_WORK_ORDER_STATUSES = ['COMPLETED', 'VERIFIED', 'CLOSED'] as const;

export const ANALYTICS_METRICS = {
  MTTR: 'MTTR',
  MTBF: 'MTBF',
  REPAIR_DURATION_PROXY: 'REPAIR_DURATION_PROXY',
  CALENDAR_AVAILABILITY: 'CALENDAR_AVAILABILITY',
  PREVENTIVE_RATIO: 'PREVENTIVE_RATIO',
  CORRECTIVE_RATIO: 'CORRECTIVE_RATIO',
  ON_TIME_COMPLETION: 'ON_TIME_COMPLETION',
  AVERAGE_RESPONSE_TIME: 'AVERAGE_RESPONSE_TIME',
} as const;
